version: "3"

services:
  application:
    image: crud-docker-mysql-app
    container_name: spring-container
    ports:
    - "8080:8080"
    networks:
      - docker-mysql
    depends_on:
      - mysqldb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb_container
    networks:
      - docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Oracle@587
      - MYSQL_DATABASE=restful_crud
networks:
       docker-mysql:


